# -*- coding: utf-8 -*-
"""3d Surface Plot: Tensile Strength Heat Map

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDHcb3PcJDByGJjZi9C3acLGoLP0Y8Vg
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Provided data
X1 = np.array([0.6, 0.6, 0.6, 1.2, 1.2, 1.2, 3.0, 3.0, 3.0])  # Independent variable 1
X2 = np.array([4.8, 6.0, 7.2, 4.8, 6.0, 7.2, 4.8, 6.0, 7.2])  # Independent variable 2
y = np.array([1.51, 5.34, 3.05, 1.35, 1.4, 1.14, 0.44, 0.38, 0.59])  # Dependent variable

# Create a meshgrid for the surface plot
x1_range = np.linspace(min(X1), max(X1),)
x2_range = np.linspace(min(X2), max(X2),)
x1_mesh, x2_mesh = np.meshgrid(x1_range, x2_range)

# Interpolate y values for the mesh points
y_interp = np.interp(x1_mesh.ravel(), X1, y)
y_interp *= np.interp(x2_mesh.ravel(), X2, y)

# Create a 3D plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plot the surface
surf = ax.plot_surface(x1_mesh, x2_mesh, y_interp.reshape(x1_mesh.shape), cmap='viridis', alpha=0.8, vmin=np.min(y), vmax=np.max(y))

# Plot the data points
ax.scatter(X1, X2, y, color='black', label='Data points')

# Set labels and title
ax.set_title('Tensile Strength (MPa)')
ax.set_xlabel('Plasticizer (g)')
ax.set_ylabel('Potato Starch (g)')
ax.set_zlabel('Tesile Strength (MPa)')
ax.set_zticks([])

# Add a colorbar to show the gradient
cbar = plt.colorbar(surf, ax=ax, shrink=0.6, aspect=10)
cbar.set_label('Tensile Strength (MPa)')

plt.show()